#!/usr/bin/env python3
"""Keep `docs/lessons/` and the index in `docs/LESSONS.md` telling the same story.

    python tools/docs/lessons.py          # check
    python tools/docs/lessons.py index    # regenerate the index, then check

One lesson per file - `L-nn.md`, under `docs/lessons/`, **the bare id as the filename**. The id is
the address a citation already carries, so a session that reads `L-73` in a task record opens the file
without asking anything first. That is why these are not slugged the way `tasks/` are: a task is
found through the board, a lesson arrives with its address in hand.

**Three checks, and the third is why this file exists.**

  1. **STALE INDEX** - an index row naming a lesson that is not there, or whose title or category
     disagrees with the file. The index is generated, so a disagreement means it was hand-edited.
  2. **ORPHAN LESSON** - a file under `docs/lessons/` with no row in the index. The other direction
     of the same fact, and both are asserted because a one-directional check on a derived copy is
     the failure **L-74** names.
  3. **DANGLING CITATION** - an `L-nn` written anywhere in the tree with no file behind it.

**Check 3 closes a gap that was open for the whole life of the document.** Lessons were one file of
89 `###` headings until 2026-08-14, cited **983 times across 165 files on the day it was split** -
and nothing resolved a single one of those citations. `refcheck.py` sees markdown links, prose `.md` paths and
`<document> §n`; taskmd's `check` sees links and front-matter. A bare `L-73` in bold prose is none
of those, so a lesson deleted or renumbered falsified up to 872 pointers with every gate green.
Storing a lesson at its own id is what makes the citation checkable, and that - not the bytes - is
what T-146 bought.

**What this tool does not do.** It never edits a lesson and it never renumbers one. The rule in the
index preamble is *add at the end of a section, never renumber*, and 872 citations are the reason.

Run it from anywhere; paths are resolved against the repository root.
"""

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
LESSON_DIR = os.path.join(ROOT, "docs", "lessons")
INDEX_PATH = os.path.join(ROOT, "docs", "LESSONS.md")

BEGIN = "<!-- lessons:begin - generated by tools/docs/lessons.py, do not edit by hand -->"
END = "<!-- lessons:end -->"

# The order the categories are printed in, which is the order they were written in the single file.
# Named rather than discovered so that a typo in one lesson's front-matter is a failure and not a
# silent fourth group.
CATEGORIES = ["Evidence and verification", "Tooling", "Writing"]

FILENAME = re.compile(r"^(L-\d+)\.md$")
HEADING = re.compile(r"^# (L-\d+) — (.+?)\s*$", re.M)
CATEGORY = re.compile(r"^category:\s*(.+?)\s*$", re.M)
CITATION = re.compile(r"\bL-(\d{2,})\b")
ROW = re.compile(r"^\| \[(L-\d+)\]\(lessons/(?:L-\d+)\.md\) \| (.+?) \| (.+?) \|$", re.M)

# Citations are counted in the files a clone receives, and only in the two kinds that carry them:
# prose and tool source. `L-07` and `L-11` are cited from a `.py`, which the index preamble says.
CITED_IN = (".md", ".py")


def read(path):
    with open(path, "r", encoding="utf-8", newline="") as fh:
        return fh.read()


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="") as fh:
        fh.write(text)


def tracked_files():
    """Every file a fresh clone receives, from `git` rather than a walk.

    The same choice `check_all.py` makes, for the same reason `refcheck.py` reads `.gitignore`: a
    gitignored working file is not part of the repository and must not be able to fail its gate.
    """
    out = subprocess.run(["git", "-C", ROOT, "ls-files"], capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit("lessons: `git ls-files` failed, so the file set cannot be established")
    return [line for line in out.stdout.splitlines() if line]


def lesson_number(name):
    return int(name.split("-")[1])


def parse_lesson(text):
    """Return `(id, title, category)` from one lesson file, or `None` if it is not shaped like one."""
    head = HEADING.search(text)
    cat = CATEGORY.search(text)
    if not head or not cat:
        return None
    return head.group(1), head.group(2), cat.group(1)


def load_lessons():
    """`{id: (title, category)}` for every file under `docs/lessons/` whose name is an id."""
    found = {}
    if not os.path.isdir(LESSON_DIR):
        return found
    for name in sorted(os.listdir(LESSON_DIR)):
        m = FILENAME.match(name)
        if not m:
            continue
        parsed = parse_lesson(read(os.path.join(LESSON_DIR, name)))
        if parsed is None:
            found[m.group(1)] = None          # present but unreadable - reported by `problems`
            continue
        ident, title, category = parsed
        found[m.group(1)] = (title, category, ident)
    return found


def load_index(text):
    """`[(id, title, category)]` from the generated block, in the order it prints them."""
    if BEGIN not in text or END not in text:
        return None
    block = text.split(BEGIN, 1)[1].split(END, 1)[0]
    return [(m.group(1), m.group(2), m.group(3)) for m in ROW.finditer(block)]


def collect_citations():
    """`{id: [paths]}` for every `L-nn` written in a tracked `.md` or `.py`."""
    cites = {}
    for rel in tracked_files():
        if not rel.endswith(CITED_IN):
            continue
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            continue
        for m in CITATION.finditer(read(path)):
            cites.setdefault("L-" + m.group(1), []).append(rel)
    return cites


def render_index(lessons):
    """The generated table: every lesson, grouped by category, in id order inside each group."""
    lines = [BEGIN, ""]
    for category in CATEGORIES:
        rows = sorted((i for i, v in lessons.items() if v and v[1] == category),
                      key=lesson_number)
        if not rows:
            continue
        lines.append("### %s" % category)
        lines.append("")
        lines.append("| | | |")
        lines.append("| :--- | :--- | :--- |")
        for ident in rows:
            title, cat, _ = lessons[ident]
            lines.append("| [%s](lessons/%s.md) | %s | %s |" % (ident, ident, title, cat))
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def problems(lessons, index, citations):
    """The three checks, over data rather than over the filesystem.

    Split out so the self-test can **construct** each failure instead of hoping the tree contains
    one (**L-85**): a fixture built from the current state of a tracked file asserts what is there,
    which is the one thing a gate must not do.
    """
    found = []
    broken = sorted((i for i, v in lessons.items() if v is None), key=lesson_number)
    for ident in broken:
        found.append(("UNREADABLE LESSON",
                      "docs/lessons/%s.md has no `# %s — title` heading or no `category:`"
                      % (ident, ident)))

    good = {i: v for i, v in lessons.items() if v}
    for ident, (title, category, declared) in sorted(good.items(), key=lambda kv: lesson_number(kv[0])):
        if declared != ident:
            found.append(("UNREADABLE LESSON",
                          "docs/lessons/%s.md calls itself %s - the filename is the address"
                          % (ident, declared)))
        if category not in CATEGORIES:
            found.append(("UNREADABLE LESSON",
                          "docs/lessons/%s.md has category %r, which is not one of the three"
                          % (ident, category)))

    if index is None:
        found.append(("STALE INDEX",
                      "docs/LESSONS.md has no generated block - run `lessons.py index`"))
        index = []

    indexed = {i: (t, c) for i, t, c in index}
    for ident in sorted(set(indexed) - set(good), key=lesson_number):
        found.append(("STALE INDEX",
                      "docs/LESSONS.md lists %s and docs/lessons/%s.md is not there"
                      % (ident, ident)))
    for ident in sorted(set(good) - set(indexed), key=lesson_number):
        found.append(("ORPHAN LESSON",
                      "docs/lessons/%s.md exists and docs/LESSONS.md does not list it"
                      % ident))
    for ident in sorted(set(good) & set(indexed), key=lesson_number):
        title, category, _ = good[ident]
        if indexed[ident] != (title, category):
            found.append(("STALE INDEX",
                          "docs/LESSONS.md gives %s as %r/%r; the file says %r/%r"
                          % (ident, indexed[ident][0], indexed[ident][1], title, category)))

    for ident in sorted(set(citations) - set(good), key=lesson_number):
        where = sorted(set(citations[ident]))
        found.append(("DANGLING CITATION",
                      "%s is cited in %d file(s) - %s - and docs/lessons/%s.md does not exist"
                      % (ident, len(where), ", ".join(where[:3]), ident)))
    return found


def cmd_index():
    lessons = load_lessons()
    text = read(INDEX_PATH)
    if BEGIN not in text or END not in text:
        sys.exit("lessons: docs/LESSONS.md has no generated block to write into")
    before, rest = text.split(BEGIN, 1)
    _, after = rest.split(END, 1)
    write(INDEX_PATH, before + render_index(lessons) + after)
    print("Wrote docs/LESSONS.md - %d lesson(s) in %d categories"
          % (len([v for v in lessons.values() if v]), len(CATEGORIES)))


def cmd_check():
    lessons = load_lessons()
    index = load_index(read(INDEX_PATH))
    citations = collect_citations()
    found = problems(lessons, index, citations)
    for kind, message in found:
        print("%-18s %s" % (kind, message))
    good = len([v for v in lessons.values() if v])
    total = sum(len(v) for v in citations.values())
    if found:
        print("\n%d problem(s) - the index, the files and the citations disagree" % len(found))
        return 1
    print("OK - %d lesson(s), %d row(s) in the index, %d citation(s) across %d file(s) resolved"
          % (good, len(index or []), total, len(set(sum(citations.values(), [])))))
    print("     this checks that a cited lesson exists. It cannot tell you the lesson is any good.")
    return 0


def self_test():
    """Refuse to run unless each of the three checks reports a failure that was put there (**L-04**).

    Every fixture below is **synthetic**. None is built from the current contents of a tracked
    file, which is the trap **L-85** records: a self-test whose expectation is *whatever is there
    now* blocks the very change it should be validating.
    """
    ok = {"L-01": ("Look at the output", "Evidence and verification", "L-01"),
          "L-40": ("Some tooling rule", "Tooling", "L-40")}
    index = [("L-01", "Look at the output", "Evidence and verification"),
             ("L-40", "Some tooling rule", "Tooling")]
    # The fixture paths carry no directory on purpose: a repo-relative `.md` path written anywhere
    # in this tree is a promise `refcheck.py` resolves, and test data must not make one.
    cites = {"L-01": ["X.md"], "L-40": ["tools/y.py"]}

    if problems(ok, index, cites):
        sys.exit("SELF-TEST FAILED: a consistent set was reported as a problem")

    kinds = lambda *args: {k for k, _ in problems(*args)}

    # 1. an index row with no file behind it
    if "STALE INDEX" not in kinds(
            {"L-01": ok["L-01"]}, index, {"L-01": ["X.md"]}):
        sys.exit("SELF-TEST FAILED: an index row naming a missing lesson was not reported")

    # 2. a file with no index row - the other direction, and the one a one-way check misses
    if "ORPHAN LESSON" not in kinds(ok, index[:1], cites):
        sys.exit("SELF-TEST FAILED: a lesson absent from the index was not reported")

    # 3. a citation of a lesson that does not exist - invisible to every other gate here
    if "DANGLING CITATION" not in kinds(ok, index, dict(cites, **{"L-77": ["Z.md"]})):
        sys.exit("SELF-TEST FAILED: a citation with no lesson behind it was not reported, which "
                 "is the whole reason this tool exists")

    # 4. a title edited in the index rather than in the lesson
    if "STALE INDEX" not in kinds(
            ok, [("L-01", "Edited by hand", "Evidence and verification"), index[1]], cites):
        sys.exit("SELF-TEST FAILED: an index row disagreeing with its file was not reported")

    # 5. a lesson whose heading names a different id from its filename
    if "UNREADABLE LESSON" not in kinds(
            dict(ok, **{"L-40": ("Some tooling rule", "Tooling", "L-41")}), index, cites):
        sys.exit("SELF-TEST FAILED: a lesson whose heading and filename disagree was not reported")

    # The index is rendered from the files, so a round trip must return what went in. Without this
    # the generator could print a table `load_index` cannot read, and every run would say STALE.
    rendered = render_index(ok)
    if load_index(rendered + "\n") != index:
        sys.exit("SELF-TEST FAILED: the generated table does not parse back to what generated it")


def main():
    argv = sys.argv[1:]
    if argv and argv[0] not in ("index", "check"):
        sys.exit(__doc__.strip().splitlines()[0] + "\n\nUsage: lessons.py [index|check]")
    self_test()
    if argv and argv[0] == "index":
        cmd_index()
        return cmd_check()
    return cmd_check()


if __name__ == "__main__":
    sys.exit(main())
