#!/usr/bin/env python
"""Task tooling for AI Training 06 — read, generate and check.

The design rule behind all of it: **store the forward edge, derive the rest.** A task file's
front-matter is the only place a fact about that task is written down. Everything else — the
child list, the "blocks" list, the index in tasks/README.md — is computed from it. Facts that
are computed cannot drift from facts that are stored.

Commands
--------
  context T-NNN   Everything needed to start work on one task, and nothing else.
                  Replaces reading CLAUDE.md + the brief + the lessons + the index +
                  the task file to find the few hundred bytes that matter.

  index           Regenerate the task tables in tasks/README.md from front-matter.
                  Hand-written sections (open decisions, standards) are preserved.

  check           Validate what is still hand-made: unknown status/phase values, references
                  to tasks that do not exist, dependency cycles, broken markdown links,
                  pointers to project documents that are not there, and (with --closing) a
                  non-empty deliverables/_working/.

Usage
-----
  python tools/tasks/task.py context T-001
  python tools/tasks/task.py index
  python tools/tasks/task.py check [--closing]

Exit code 0 on success, 1 on any problem. Pure standard library, by L-07. Console output is
ASCII — the Windows console mangles em-dashes under cp1252.
"""

import fnmatch
import glob
import os
import re
import sys

# The Windows console defaults to cp1252, which mangles accented characters and
# typographic punctuation. Task content is UTF-8, so say so rather than losing characters.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
INDEX = "tasks/README.md"
DECISIONS = "tasks/DECISIONS.md"
WORKING = os.path.join("deliverables", "_working")

# The documents this tooling, the templates and the prose send a reader to. Each one is a
# promise that the file is there, and this repository has to be clone-and-run (CLAUDE.md), so
# `check` requires them. Named here so the pointer that gets printed and the pointer that gets
# checked cannot drift apart - `check` reported "0 broken links" while two of these did not
# exist at all, because it only ever looked at markdown links between task files (L-09).
WORKFLOW = "tasks/TASK-WORKFLOW.md"
LESSONS = "docs/LESSONS.md"
PROJECT_DOCS = {
    "CLAUDE.md": "the working conventions every task inherits",
    "docs/BRIEF.md": "what to build and why",
    LESSONS: "the carried lessons, cited as L-nn and printed by `context`",
    WORKFLOW: "the task schema; printed by `context`, cited by the task template",
    INDEX: "the generated task index",
}
# Referenced conditionally, so absent is a valid state rather than a broken pointer: the
# decisions register is created the first time a task carries `decisions:`, and load_decisions
# treats a missing file as an empty register.
OPTIONAL_DOCS = {DECISIONS}

BEGIN = "<!-- generated by tools/tasks/task.py - do not edit by hand -->"
END = "<!-- end generated -->"

# The vocabulary. Anything outside these is a typo, and `check` says so.
STATUSES = ["proposed", "specified", "planned", "in_progress", "blocked",
            "review", "done", "cancelled"]
OPEN_STATUSES = [s for s in STATUSES if s not in ("done", "cancelled")]
PHASES = ["specify", "plan", "implement", "review"]

LINK = re.compile(r"\[[^\]]*\]\(([^)#\s]+)(?:#[^)\s]*)?\)")
SCALAR = re.compile(r"^(\w+):[ \t]*(.*?)[ \t]*$", re.M)

# A pointer written as prose - `docs/LESSONS.md` in a sentence, in a template comment, or in a
# string a tool prints - is as much a promise as a markdown link, and nothing checked those.
# Requires a slash, so a bare "README.md" in prose is not mistaken for a path to somewhere;
# a glob such as docs/research/R1-*.md cannot match, which is deliberate.
POINTER = re.compile(r"(?<![\w./-])((?:\w|\.\.?)[\w.-]*(?:/[\w.-]+)+\.md)\b")

# ---------------------------------------------------------------- section references (§6.1)
# The rule is in TASK-WORKFLOW.md §6.1 and this implements it. Both halves exist so the number a
# reference cites is PRINTED in the document it points at.
DOC_STEMS = "DESIGN-SYSTEM|DESIGN-RATIONALE|EVALUATION|BRIEF|TASK-WORKFLOW|LESSONS"

# **Adjacency is the whole of the binding.** A document named earlier in the paragraph is not the
# target: tried against the corpus, "nearest document mentioned" picked the wrong file for a third
# of the misses it reported - `R4-prior-art.md` for a §2.1 that meant the citing document's own.
# So the name and the mark may be separated only by markdown punctuation and at most one space.
SECTION_REF = re.compile(
    r"(?P<doc>[A-Za-z0-9_./-]+\.md|\bR[1-9]\b|\bT-\d{3}\b|\b(?:%s)\b)"
    r"[`*\]\)_,]{0,4}[ ]?[`*\]\)_]{0,3}[ ]?§(?P<sec>\d+(?:\.\d+)*)" % DOC_STEMS)
SECTION_ANY = re.compile(r"§\d+(?:\.\d+)*")

# A numbered heading: `## 3.` or `### 2.1 ` - the trailing dot is optional because both forms are
# in use.
NUM_HEADING = re.compile(r"^#{1,6}\s+(\d+(?:\.\d+)*)\.?\s", re.M)
ANY_HEADING = re.compile(r"^#{1,6}\s", re.M)
ORDINAL = re.compile(r"^\s{0,3}(\d+)\.\s", re.M)

# Code is literal text, not a pointer. This is what lets a document quote a reference that is
# WRONG - the audit that found this family wrote `DESIGN-SYSTEM.md §11` a dozen times to say it
# never existed, and under any other rule the record of a dead pointer is itself one.
FENCE = re.compile(r"^```.*?^```", re.M | re.S)
CODE_SPAN = re.compile(r"`[^`\n]*`")


def strip_code(text):
    """Blank out fenced blocks and code spans, preserving offsets and line structure."""
    blank = lambda m: re.sub(r"[^\n]", " ", m.group(0))     # noqa: E731
    return CODE_SPAN.sub(blank, FENCE.sub(blank, text))


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def doc_aliases(paths):
    """Every name a document can be cited by -> its path.

    `DESIGN-SYSTEM.md`, `DESIGN-SYSTEM`, `R7`, `T-042`. Derived from the filenames present, so a
    renamed document changes what resolves without anything here being edited (**L-08**).
    """
    alias = {}
    for p in paths:
        if not p.endswith(".md"):
            continue
        base = os.path.basename(p)
        alias.setdefault(base.upper(), p)
        alias.setdefault(base[:-3].upper(), p)
        for pat in (r"^(R[1-9])-", r"^(T-\d{3})-"):
            m = re.match(pat, base[:-3])
            if m:
                alias.setdefault(m.group(1).upper(), p)
    return alias


def section_index(path):
    """(numbered headings, {heading: ordinals printed in a numbered list under it})."""
    return section_index_of(read(path))


def section_index_of(text):
    heads, ordinals = set(), {}
    starts = [m.start() for m in ANY_HEADING.finditer(text)]
    for m in NUM_HEADING.finditer(text):
        heads.add(m.group(1))
        nxt = next((s for s in starts if s > m.start()), len(text))
        found = {o.group(1) for o in ORDINAL.finditer(text[m.start():nxt])}
        ordinals.setdefault(m.group(1), set()).update(found)
    return heads, ordinals


def section_resolves(index, ref):
    """TASK-WORKFLOW.md §6.1: a heading, or a heading plus an ordinal printed under it."""
    heads, ordinals = index
    if ref in heads:
        return True
    if "." in ref:
        n, m = ref.rsplit(".", 1)
        return n in heads and m in ordinals.get(n, set())
    return False


def write(path, text):
    # newline="\n" so output is identical on every platform (L-11).
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def parse_list(raw):
    """[T-001, T-002] -> ['T-001', 'T-002']; '' / [] / null -> []."""
    raw = (raw or "").strip()
    if not raw or raw in ("[]", "null", "none", "None"):
        return []
    return [item.strip() for item in raw.strip("[]").split(",") if item.strip()]


class Task(object):
    def __init__(self, path):
        self.path = path.replace("\\", "/")
        self.name = os.path.basename(self.path)
        text = read(path)
        end = text.find("\n---", 3) if text.startswith("---") else -1
        fm = text[3:end] if end != -1 else ""
        self.fields = dict(SCALAR.findall(fm))

        self.id = self.fields.get("id", "")
        self.title = self.fields.get("title", "")
        self.status = self.fields.get("status", "")
        self.phase = self.fields.get("phase", "")
        self.type = self.fields.get("type", "")
        self.wp = self.fields.get("work_package", "none")
        self.owner = self.fields.get("owner", "")

        parent = (self.fields.get("parent") or "").strip()
        self.parent = "" if parent in ("", "null", "none", "None") else parent
        self.blocked_by = parse_list(self.fields.get("blocked_by"))
        self.related = parse_list(self.fields.get("related"))
        self.decisions = parse_list(self.fields.get("decisions"))
        # `deliverables:` comes in both forms. Written as a block list its items are on the
        # following lines, so it needs the raw front-matter rather than the scalar map; written
        # inline - which is what every task file actually does - it is a scalar. Parse both, or
        # the whole thing reads as "no task declares any output". Trailing "# comment" stripped.
        block = re.search(r"^deliverables:[ \t]*\n((?:[ \t]+-.*\n?)*)", fm, re.M)
        items = (re.findall(r"^[ \t]+-[ \t]*(.+)$", block.group(1), re.M) if block
                 else parse_list(self.fields.get("deliverables")))
        self.outputs = [item.split("#")[0].strip() for item in items if item.split("#")[0].strip()]

        # Derived — never stored.
        self.children = []
        self.blocks = []

    @property
    def is_open(self):
        return self.status in OPEN_STATUSES


def load():
    """Read every task file and wire up the derived (inverse) edges."""
    os.chdir(ROOT)
    tasks = {}
    for path in sorted(glob.glob(os.path.join("tasks", "T-*.md"))):
        t = Task(path)
        if t.id:
            tasks[t.id] = t

    for t in tasks.values():
        if t.parent in tasks:
            tasks[t.parent].children.append(t.id)
        for upstream in t.blocked_by:
            if upstream in tasks:
                tasks[upstream].blocks.append(t.id)
    return tasks


def line(t, tasks):
    """One-line summary of a task, for use inside another task's context."""
    return "%s  %-11s %s" % (t.id, t.status, t.title)


def project_files(exts=(".md",)):
    """Every file with one of `exts`, including dot-directories that glob's ** skips."""
    for base, dirs, files in os.walk("."):
        dirs[:] = [d for d in dirs if d not in (".git", "node_modules", "__pycache__")]
        for f in files:
            if f.endswith(exts):
                yield os.path.normpath(os.path.join(base, f))


def markdown_files():
    return project_files((".md",))


def gitignore_patterns():
    """What .gitignore excludes. Those paths are absent from a fresh clone by design - the
    corpus knowledgebase carries private data, the live handoff state is machine-local - so a
    pointer to one is not a pointer that fails for the reader."""
    patterns = []
    if os.path.exists(".gitignore"):
        for ln in read(".gitignore").splitlines():
            ln = ln.strip()
            if ln and not ln.startswith("#"):
                patterns.append(ln.strip("/"))
    return patterns


def is_ignored(rel, patterns):
    rel = rel.replace("\\", "/")
    for pat in patterns:
        if "/" in pat:
            if fnmatch.fnmatch(rel, pat) or fnmatch.fnmatch(rel, pat + "/*"):
                return True
        elif any(fnmatch.fnmatch(part, pat) for part in rel.split("/")):
            return True
    return False


def strip_front_matter(text):
    """The pointer scan reads prose, and front-matter is not prose - it is the structured
    record the loader parses and `check` validates by other means. `deliverables:` is the case
    that forces the distinction: it names outputs a task has not produced yet, so scanning it
    would make declaring one impossible, and `task.py deliverables` exists to report on exactly
    those. Replaced with blank lines rather than removed, so nothing downstream shifts."""
    m = re.match(r"---\r?\n.*?\r?\n---\r?\n", text, re.S)
    return "\n" * text[:m.end()].count("\n") + text[m.end():] if m else text


def resolves(target, base):
    """A pointer may be written from the repository root - the form a tool prints - or
    relative to the file it appears in. Either is fine; neither existing is not."""
    for candidate in (target, os.path.join(base, target)):
        if os.path.exists(os.path.normpath(candidate)):
            return True
    return False


def points_into_repo(target, base):
    """Whether a path-shaped string is a promise about *this* repository at all.

    Research notes quote other projects' layouts - `references/libraries.md` inside the deck
    skill, `humanize-writing/SKILL.md` - and those are citations, not pointers a reader is
    meant to follow here. The test that separates them: the directory the path names has to
    exist, from the root or beside the citing file. A missing file under `docs/` is still
    caught, because that directory is real; `references/libraries.md` is not, because no
    `references/` is. (Writing that example out as a path would trip this very check - which is
    the check working.)

    The hole this leaves is a typo in the directory itself - `doc/BRIEF.md` reads as somebody
    else's tree and is skipped. `PROJECT_DOCS` covers the documents that matter most by name,
    which is why that list exists separately."""
    head = target.replace("\\", "/").split("/")[0]
    if head in ("", ".", ".."):
        return True
    return any(os.path.isdir(os.path.normpath(c)) for c in (head, os.path.join(base, head)))


def load_decisions():
    """Parse the D-NNN rows out of tasks/DECISIONS.md. That table is the source; which
    tasks a decision blocks is derived from the tasks' `decisions:` fields."""
    register = {}
    if not os.path.exists(DECISIONS):
        return register
    for ln in read(DECISIONS).splitlines():
        if not ln.startswith("| D-"):
            continue
        cells = [c.strip() for c in ln.strip("|").split("|")]
        if len(cells) >= 4:
            register[cells[0]] = {"id": cells[0], "status": cells[1],
                                  "owner": cells[2], "question": cells[3],
                                  "blocks": []}
    return register


# --------------------------------------------------------------------------- context

def cmd_context(args):
    if not args:
        print("usage: task.py context T-NNN")
        return 1
    wanted = args[0].upper()
    tasks = load()
    if wanted not in tasks:
        print("No such task: %s" % wanted)
        return 1

    t = tasks[wanted]
    out = []
    out.append("=" * 72)
    out.append("%s  %s" % (t.id, t.title))
    out.append("=" * 72)
    out.append("status %s | phase %s | type %s | wp %s | owner %s"
               % (t.status, t.phase, t.type, t.wp, t.owner))
    out.append("file   %s" % t.path)

    blockers = [tasks[b] for b in t.blocked_by if b in tasks]
    open_blockers = [b for b in blockers if b.is_open]
    if blockers:
        out.append("")
        out.append("BLOCKED BY  (must land first)")
        for b in blockers:
            flag = "  <-- still open" if b.is_open else ""
            out.append("  " + line(b, tasks) + flag)

    if t.blocks:
        out.append("")
        out.append("BLOCKS  (waiting on this one)")
        # `context` keeps closed downstream tasks where the board drops them - it is read to
        # *do* one task, and the closed ones are the trail explaining why it exists. They are
        # marked, because the heading above claims they are waiting and they are not.
        for b in t.blocks:
            flag = "" if tasks[b].is_open else "  <-- closed, not waiting"
            out.append("  " + line(tasks[b], tasks) + flag)

    if t.parent and t.parent in tasks:
        out.append("")
        out.append("PARENT")
        out.append("  " + line(tasks[t.parent], tasks))

    if t.children:
        out.append("")
        out.append("CHILDREN")
        for c in t.children:
            out.append("  " + line(tasks[c], tasks))

    if t.related:
        out.append("")
        out.append("RELATED  (context, not a dependency)")
        for r in t.related:
            if r in tasks:
                out.append("  " + line(tasks[r], tasks))

    register = load_decisions()
    linked = [register[d] for d in t.decisions if d in register]
    open_decisions = [d for d in linked if d["status"] != "closed"]
    if linked:
        out.append("")
        out.append("DECISIONS  (%s)" % DECISIONS)
        for d in linked:
            flag = "  <-- UNANSWERED" if d["status"] != "closed" else ""
            out.append("  %s %-7s %s%s"
                       % (d["id"], d["status"], d["question"][:70], flag))

    if t.outputs:
        out.append("")
        out.append("PRODUCES")
        for path in t.outputs:
            out.append("  [%s] %s" % ("x" if os.path.exists(path) else " ", path))

    out.append("")
    if open_blockers:
        out.append("NEXT: blocked - clear %s first."
                   % ", ".join(b.id for b in open_blockers))
    elif open_decisions:
        out.append("NEXT: needs a decision from %s - %s."
                   % (open_decisions[0]["owner"],
                      ", ".join(d["id"] for d in open_decisions)))
    else:
        out.append("NEXT: read the file above, then work the '%s' phase." % t.phase)
    out.append("Rules: %s   Lessons: %s" % (WORKFLOW, LESSONS))

    print("\n".join(out))
    return 0


# --------------------------------------------------------------------------- index

def table(rows, header):
    out = [header, "| " + " | ".join([":---"] * header.count("|") and
                                      [":---"] * (header.count("|") - 1)) + " |"]
    # Rebuild the separator to match the header's column count exactly.
    cols = header.count("|") - 1
    out[1] = "|" + "|".join([" :--- "] * cols) + "|"
    out.extend(rows)
    return out


def cmd_index(args):
    tasks = load()
    ordered = sorted(tasks.values(), key=lambda t: t.id)

    active, closed = {}, []
    for t in ordered:
        link = "[%s](%s)" % (t.id, t.name)
        if t.is_open:
            # Both sides of the same edge, filtered the same way: the board counts only open
            # tasks as gated (TASK-WORKFLOW.md §6). A closed blocker no longer gates, and a
            # closed downstream task is no longer waiting - listing it overstates how much
            # this row unblocks, which is criterion (a) of T-030's tie-break rule.
            blockers = ", ".join(b for b in t.blocked_by
                                 if b in tasks and tasks[b].is_open) or "-"
            downstream = ", ".join(b for b in t.blocks if tasks[b].is_open) or "-"
            active.setdefault(t.wp, []).append(
                "| %s | %s | `%s` | %s | %s | %s |"
                % (link, t.title, t.status, t.phase, blockers, downstream))
        else:
            closed.append("| %s | %s | `%s` | %s |"
                          % (link, t.title, t.status,
                             t.fields.get("updated", "")))

    nxt = max(int(t.id.split("-")[1]) for t in ordered) + 1

    block = [BEGIN, ""]
    block.append("## Active")
    block.append("")
    if active:
        # **One section per work package, not one table with a WP column.** The board is read to
        # CHOOSE what to work on (TASK-WORKFLOW.md §6), and since the backlog became two release
        # phases the first question a reader has is *which of these is between here and a
        # release* - a question a column answers only after they have sorted it in their head.
        # The heading also gives each phase somewhere to be linked to.
        for wp in sorted(active):
            block.append("### %s" % wp)
            block.append("")
            block.append("| ID | Title | Status | Phase | Blocked by | Blocks |")
            block.append("| :--- | :--- | :--- | :--- | :--- | :--- |")
            block.extend(active[wp])
            block.append("")
    else:
        block.append("_None._")
        block.append("")
    block.append("## Closed")
    block.append("")
    block.append("| ID | Title | Status | Updated |")
    block.append("| :--- | :--- | :--- | :--- |")
    block.extend(closed)
    block.append("")
    block.append("## Next ID")
    block.append("")
    block.append("`T-%03d`" % nxt)
    block.append("")
    block.append(END)

    text = read(INDEX)
    generated = "\n".join(block)
    if BEGIN in text and END in text:
        head = text[:text.index(BEGIN)]
        tail = text[text.index(END) + len(END):]
        text = head + generated + tail
    else:
        text = text.rstrip() + "\n\n" + generated + "\n"
    write(INDEX, text)
    print("Regenerated %s - %d active in %d work package(s), %d closed, next T-%03d"
          % (INDEX, sum(len(v) for v in active.values()), len(active), len(closed), nxt))
    return 0


# --------------------------------------------------------------------------- check

def cmd_check(args):
    closing = "--closing" in args
    tasks = load()
    register = load_decisions()
    problems, warnings = [], []

    for t in sorted(tasks.values(), key=lambda x: x.id):
        if t.status not in STATUSES:
            problems.append("BAD STATUS   %s has `%s`; allowed: %s"
                            % (t.id, t.status, ", ".join(STATUSES)))
        if t.phase not in PHASES:
            problems.append("BAD PHASE    %s has `%s`; allowed: %s"
                            % (t.id, t.phase, ", ".join(PHASES)))
        if "children" in t.fields:
            problems.append("STALE FIELD  %s still has `children:` - it is derived from "
                            "`parent:` now; remove it" % t.id)
        for ref, field in ([(t.parent, "parent")] if t.parent else []) + \
                          [(r, "blocked_by") for r in t.blocked_by] + \
                          [(r, "related") for r in t.related]:
            if ref not in tasks:
                problems.append("DANGLING     %s.%s -> %s does not exist"
                                % (t.id, field, ref))
        if t.status == "blocked" and not t.blocked_by:
            problems.append("NO BLOCKER   %s is `blocked` with an empty `blocked_by`" % t.id)
        for d in t.decisions:
            if d not in register:
                problems.append("DANGLING     %s.decisions -> %s is not in %s"
                                % (t.id, d, DECISIONS))

    # A blocks B blocks A would deadlock the backlog silently.
    seen, stack = set(), set()

    def walk(tid):
        if tid in stack:
            problems.append("CYCLE        dependency loop through %s" % tid)
            return
        if tid in seen or tid not in tasks:
            return
        stack.add(tid)
        for up in tasks[tid].blocked_by:
            walk(up)
        stack.discard(tid)
        seen.add(tid)

    for tid in sorted(tasks):
        walk(tid)

    # glob's ** skips dot-directories, which hid .handoff/ and .claude/ - and .handoff/HANDOFF.md
    # is the live resume pointer, the one file where a broken link costs the most. Walk instead.
    # `.gitignore` governs here too, and it did not until T-045 tripped over the difference: an
    # archived, machine-local handoff was link-checked as though a fresh clone contained it, which
    # is the opposite of the question the prose scan below says both scans are answering. The live
    # `.handoff/HANDOFF.md` is the reason this walk reaches dot-directories at all, and it is
    # excluded by the same rule - so the check that matters most is the one this drops. That is
    # correct: it is not in the clone either, and `handoff` owns it.
    link_ignore = gitignore_patterns()
    for md in sorted(markdown_files()):
        if is_ignored(os.path.relpath(md, "."), link_ignore):
            continue
        base = os.path.dirname(md)
        for m in LINK.finditer(read(md)):
            target = m.group(1)
            if target.startswith(("http://", "https://", "mailto:")):
                continue
            if not os.path.exists(os.path.normpath(os.path.join(base, target))):
                problems.append("BROKEN LINK  %s -> %s" % (md, target))

    for doc in sorted(PROJECT_DOCS):
        if not os.path.exists(os.path.normpath(doc)):
            problems.append("MISSING DOC  %s is pointed at but does not exist - %s"
                            % (doc, PROJECT_DOCS[doc]))

    # Prose and printed pointers. The question this answers is narrow - would a reader who just
    # cloned this repository find the file? So .gitignore decides on both sides: an excluded
    # path is not a broken pointer, and an excluded *document* is not scanned at all, because it
    # is not in the clone either.
    #
    # There used to be a third exemption: any path some task declared as a deliverable was
    # skipped, on the grounds that it was a promise about the future. It was deleted (T-029),
    # because it exempted the path *everywhere in the repository, forever*, including files that
    # already existed - declaring `docs/LESSONS.md` silently dropped six live pointers out of
    # validation and `check` still printed "0 broken" (L-05). What replaces it is narrower by
    # construction: front-matter is not prose, so it is not scanned. `deliverables:` is a
    # declaration that `task.py deliverables` reports on, not a pointer sending a reader
    # anywhere, and skipping the field cannot widen to cover a mention somewhere else.
    ignore = gitignore_patterns()

    pointers, seen_pointers, skipped = 0, set(), 0
    for src in sorted(project_files((".md", ".py"))):
        if is_ignored(os.path.relpath(src, "."), ignore):
            skipped += 1
            continue
        base = os.path.dirname(src)
        for m in POINTER.finditer(strip_front_matter(read(src))):
            target = m.group(1)
            if target in OPTIONAL_DOCS or is_ignored(target, ignore):
                continue
            if not points_into_repo(target, base):
                continue
            pointers += 1
            if (src, target) in seen_pointers:
                continue          # one report per document per target, not one per mention
            seen_pointers.add((src, target))
            if not resolves(target, base):
                problems.append("DEAD POINTER %s -> %s does not exist" % (src, target))

    # ---- section references (TASK-WORKFLOW.md §6.1)
    scanned = [s for s in sorted(project_files((".md", ".py")))
               if not is_ignored(os.path.relpath(s, "."), ignore)]
    alias = doc_aliases(scanned)
    sec_index, sections, sec_skipped, seen_sections = {}, 0, 0, set()
    for src in scanned:
        text = strip_code(strip_front_matter(read(src)))
        bound = set()
        for m in SECTION_REF.finditer(text):
            bound.add(m.start("sec"))
            tok, ref = m.group("doc"), m.group("sec")
            target = None
            if "/" in tok:
                cand = os.path.normpath(os.path.join(os.path.dirname(src), tok))
                target = cand if os.path.exists(cand) else None
            target = target or alias.get(os.path.basename(tok).upper())
            if not target:
                sec_skipped += 1              # a name this repository does not carry
                continue
            sections += 1
            if target not in sec_index:
                sec_index[target] = section_index(target)
            if section_resolves(sec_index[target], ref):
                continue
            key = (src, target, ref)
            if key in seen_sections:
                continue                      # one report per document per target section
            seen_sections.add(key)
            problems.append("DEAD SECTION %s -> %s has no §%s"
                            % (src, os.path.relpath(target, "."), ref))
        # Every mark the citation form does not bind to a document. Counted, never dropped: a
        # scan that silently ignores what it cannot bind is the report this tool exists not to be.
        sec_skipped += len([m for m in SECTION_ANY.finditer(text)
                            if m.start() + 1 not in bound])

    # git carries no empty directory, so `os.path.isdir` false meant "nothing left over" in every
    # fresh clone and `--closing` reported the stricter run having done one test fewer than it
    # claimed (**L-05**). Absent is now its own answer.
    if not os.path.isdir(WORKING):
        msg = "%s does not exist, so the leftover-file check had nothing to run against" % WORKING
        (problems if closing else warnings).append(
            ("NO WORKING DIR " if closing else "note: ") + msg)
    else:
        leftovers = os.listdir(WORKING)
        if leftovers:
            msg = "%s not empty: %s" % (WORKING, ", ".join(sorted(leftovers)))
            (problems if closing else warnings).append(
                ("NOT EMPTY    " if closing else "note: ") + msg)

    # ---- what an open task owes the report (TASK-WORKFLOW.md §6.2)
    for t in sorted(tasks.values(), key=lambda x: x.id):
        if t.is_open and t.status != "proposed" and not t.outputs:
            problems.append("NO DELIVERABLE %s is %r and declares none - `deliverables:` is the "
                            "only place an unproduced output is written as a path" % (t.id, t.status))

    for w in warnings:
        print(w)
    if problems:
        print("\nFAIL - %d problem(s):\n" % len(problems))
        for p in problems:
            print("  " + p)
        return 1
    # Say what was checked, not just that it passed: this line used to read "0 broken links"
    # while two documents the tool itself points at were missing (L-05).
    print("OK - %d tasks, vocabulary valid, task references resolve, "
          "%d document pointer(s) checked, 0 broken" % (len(tasks), pointers))
    print("     %d section reference(s) resolved, 0 dead; %d not bound to a document and skipped."
          % (sections, sec_skipped))
    # And say what was *not* checked. A count that silently shrinks is the failure T-029 was
    # raised for: declaring one existing file as a deliverable dropped six pointers out of this
    # number, and the line above still read "0 broken".
    print("     %d document(s) not scanned (.gitignore); front-matter is not scanned."
          % skipped)
    print("     structure and references only - it cannot tell you a spec or a "
          "deliverable is any good.")
    return 0


def cmd_decisions(args):
    """Every decision, and - derived from the tasks - what it is holding up."""
    tasks = load()
    register = load_decisions()
    for t in tasks.values():
        for d in t.decisions:
            # Open only - the same rule the board applies to `blocks` and `blocked_by`
            # (TASK-WORKFLOW.md §6). A closed task is not held up by anything.
            if d in register and t.is_open:
                register[d]["blocks"].append(t.id)

    if not register:
        print("No decisions register at %s" % DECISIONS)
        return 1
    for d in sorted(register.values(), key=lambda x: x["id"]):
        held = ", ".join(sorted(d["blocks"])) or "-"
        mark = " " if d["status"] == "closed" else "!"
        print("%s %s  %-7s  owner %-6s  blocks %s"
              % (mark, d["id"], d["status"], d["owner"], held))
        print("    %s" % d["question"])
    unanswered = [d for d in register.values() if d["status"] != "closed" and d["blocks"]]
    print("\n%d decision(s) currently holding up open work." % len(unanswered))
    return 0


def cmd_deliverables(args):
    """What every task declares it produces, and whether it exists yet. Derived - there is
    no deliverable list to maintain."""
    tasks = load()
    open_rows, closed_rows, silent = [], [], []
    for t in sorted(tasks.values(), key=lambda x: (x.wp, x.id)):
        if t.is_open and not t.outputs:
            silent.append((t.id, t.status))
        for path in t.outputs:
            row = (t.wp, t.id, t.status, "x" if os.path.exists(path) else " ", path)
            (open_rows if t.is_open else closed_rows).append(row)
    if not open_rows and not closed_rows:
        print("No task declares any deliverables.")
        return 0

    def table(title, rows):
        print("\n%s" % title)
        if not rows:
            print("  (none)")
            return
        print("  %-5s %-6s %-11s %s  %s" % ("WP", "TASK", "STATUS", "?", "PATH"))
        for wp, tid, status, mark, path in rows:
            print("  %-5s %-6s %-11s [%s] %s" % (wp, tid, status, mark, path))

    # **Open and closed are reported apart on purpose** (TASK-WORKFLOW.md §6.2). Together, one
    # outstanding output hid among seventy delivered ones and the summary read "0 not on disk
    # yet" - structurally true, because every open task declared none (**L-05**).
    table("OUTSTANDING - declared by an open task", open_rows)
    table("DELIVERED - declared by a closed task", closed_rows)
    out_missing = len([r for r in open_rows if r[3] != "x"])
    print("\n%d output(s) declared by open tasks, %d of them not on disk yet."
          % (len(open_rows), out_missing))
    print("%d declared by closed tasks; %d of those absent, which would be a defect."
          % (len(closed_rows), len([r for r in closed_rows if r[3] != "x"])))
    if silent:
        print("\n%d open task(s) declare no deliverable at all:" % len(silent))
        for tid, status in silent:
            print("  %-6s %-11s %s" % (tid, status,
                                       "correct - a proposal need not know yet"
                                       if status == "proposed" else "**a `check` failure**"))
    return 0


def self_test():
    """Refuse to run if the checks cannot tell a good reference from a bad one (**L-04**).

    This tool had no self-test until T-046, which is why three of its reports could not fail:
    a section resolver that did not exist, a deliverables column that was structurally zero, and
    a `--closing` test that no-opped in every fresh clone. Each assertion below **constructs the
    failure** and requires it to be reported - an assertion that only ever sees the passing case
    is the same defect one level up.
    """
    # A miniature of the two documents that decide the rule: a §0 whose numbered list runs to 8,
    # a §5 with three items and a real §5.1 subsection, and a §9 with no list under it.
    idx = section_index_of(
        "# T\n\n## 0. Preamble\n\n" + "".join("%d. item\n" % i for i in range(9)) +
        "\n## 5. Five\n\n1. first\n2. second\n3. third\n\n### 5.1 Sub\n\n## 9. Nine\n\nprose\n")

    # The four cases that decide the rule (TASK-WORKFLOW.md §6.1), plus the two shapes each side.
    # Two must pass and two must fail; a resolver that says yes to everything satisfies only the
    # first pair, which is why the second is here.
    for ref in ("5", "5.1", "5.3", "0.8"):
        if not section_resolves(idx, ref):
            sys.exit("SELF-TEST FAILED: §%s should resolve - a heading, or an ordinal under one"
                     % ref)
    for ref in ("9.4", "0.9", "11"):
        if section_resolves(idx, ref):
            sys.exit("SELF-TEST FAILED: §%s does not exist and was reported as resolving" % ref)

    # Adjacency binds a reference to a document; proximity does not. Both halves are asserted,
    # because the loose version passed the first and produced wrong targets on the second.
    # The fixtures name documents this repository does not carry, so the scan over this file does
    # not read its own test data as live pointers - which it did, and reported two.
    if not SECTION_REF.search("see [EXAMPLE.md](EXAMPLE.md) §2 for the rest"):
        sys.exit("SELF-TEST FAILED: a linked document followed by a section mark did not bind")
    if not SECTION_REF.search("EXAMPLE.md §5.3 covers it"):
        sys.exit("SELF-TEST FAILED: a bare document name beside a section mark did not bind")
    if SECTION_REF.search("EXAMPLE.md is the source, and the reasoning is in §2.1"):
        sys.exit("SELF-TEST FAILED: a document named earlier in the sentence was bound to a "
                 "later section mark - that is the heuristic T-046 rejected")

    # Code is literal text. Without this a document cannot record that a pointer is dead.
    if "§11" in strip_code("the note cites `DESIGN-SYSTEM.md §11`, which never existed"):
        sys.exit("SELF-TEST FAILED: a section mark inside a code span was not treated as literal")
    if "§9" not in strip_code("cites DESIGN-SYSTEM.md §9 in prose"):
        sys.exit("SELF-TEST FAILED: stripping code removed a mark that was not in code")
    return True


COMMANDS = {"context": cmd_context, "index": cmd_index, "check": cmd_check,
            "decisions": cmd_decisions, "deliverables": cmd_deliverables}


def main():
    argv = sys.argv[1:]
    if not argv or argv[0] not in COMMANDS:
        print(__doc__.split("Usage")[1].strip() if "Usage" in __doc__ else "")
        print("commands: " + ", ".join(sorted(COMMANDS)))
        return 1
    os.chdir(ROOT)
    self_test()
    return COMMANDS[argv[0]](argv[1:])


if __name__ == "__main__":
    sys.exit(main())
